[package]
name = "server"
version = "0.1.0"
authors = ["Kyle McKean <mckean.kylej@gmail.com>"]

[dependencies]
nickel = "0.8.0"
diesel = "0.7.1"
diesel_codegen = { version = "0.7.2", features = ["postgres"] }
dotenv = "0.8.0"
dotenv_macros = "0.9.0"
